### ISSUE TITLE
Suggestion to bring previous feature back

### ISSUE THREAD

**Issue by brainscar** [intika/Librefox#100]
Hi :)

I remember in earlier releases it was recommended to delete several files:

updater (executable), updater.ini, crashreporter (executable), crashreport.conf etc. (also, I found pingsender executable in that same directory).

Maybe we can bring the suggestion to delete those files back?

Also several default .xpi files can be deleted safely.

Thank you!

**Comment by intika** [comment]
They are currently disabled with the settings on the mozilla.cfg etc... i was deleting them to double patch (setting and remove the code)... i don't want to make the install process too complicated for the current version it's why i removed those instructions. 

But sure the feature will be back/included for sure once i finish v3 i am also removing integrated xpi (that mozilla hard-coded in firefox).

It's already in the plan :) :+1:

**Comment by brainscar** [comment]
Thank you @intika
