### ISSUE TITLE
Prefs update v65

### ISSUE THREAD

**Issue by Atavic** [intika/Librefox#102]
*network.connectivity-service* [prefs in FF 65](https://github.com/ghacksuserjs/ghacks-user.js/issues/610):

```javascript
pref("network.connectivity-service.DNSv4.domain", "mozilla.org");
pref("network.connectivity-service.DNSv6.domain", "mozilla.org");
pref("network.connectivity-service.enabled", true);
pref("network.connectivity-service.IPv4.url", "http://detectportal.firefox.com/success.txt?ipv4");
pref("network.connectivity-service.IPv6.url", "http://detectportal.firefox.com/success.txt?ipv6");
```

...are a group of unneeded entries unless you use [Sync account](https://github.com/intika/Librefox/issues/30) and maybe [Push notifcations](https://github.com/intika/Librefox/issues/1).

Windows NCSI is exactly the same as FF *network.connectivity-service* prefs, as both do:

- A DNS query respectively to *dns.msftncsi.com* & *mozilla.org*

- A HTTP query that gets a mere text, respectively ```Microsoft NCSI``` and ```success``` from:

```http://www.msftncsi.com/ncsi.txt``` and ```http://detectportal.firefox.com/success.txt```

These FF 65 entries go against the security principle of a reduced attack surface, as there's a DNS Hijack opportunity.

**Comment by intika** [comment]
Great thanks for reporting back i'll take care of that ;)
