### ISSUE TITLE
"Recommended by undefined"

### ISSUE THREAD

**Issue by shreyasminocha** [intika/Librefox#113]
In `about:preferences#home`, under "Firefox Home Content", there's "Recommended by undefined".

**Comment by intika** [comment]
This is disabled any way the "undefined" is probably caused by the zero network communication feature

**Comment by intika** [comment]
This will be followed here https://github.com/intika/Librefox/issues/3

**Comment by shreyasminocha** [comment]
Yes. If there's a way to easily fix this, great. Otherwise we can let it be.

**Comment by intika** [comment]
it's approved and added to the tasks i will check that out when i'll be working on that feature

**Comment by Atavic** [comment]
It is related to the snippets service.
