### ISSUE TITLE
Add deb releases

### ISSUE THREAD

**Issue by darthoctopus** [intika/Librefox#25]
Please consider incorporating [Ubuntu's global menubar patch](http://bazaar.launchpad.net/~mozillateam/firefox/firefox-trunk.head/view/head:/debian/patches/unity-menubar.patch) for better integration with desktop environments that support global menus, such as KDE Plasma and MATE or XFCE with the appmenu extension.

**Comment by Atavic** [comment]
I think this should be done by some specific fork.

**Comment by intika** [comment]
I will see what i can do for next release and let you know :)
Thanks for your contribution and feedback.

**Comment by intika** [comment]
this issue will be followed here https://github.com/intika/Librefox/issues/27
