### ISSUE TITLE
(LEGAL) Change about:license text. Change about:rights text.

### ISSUE THREAD

**Issue by Peacock365** [intika/Librefox#38]
At the very top of the **about:license** page, one can read the following statement:

_"Binaries of this product have been made available to you by the [Mozilla Project](https://www.mozilla.org/en-US/) under the Mozilla Public License 2.0 (MPL). [Know your rights](about:rights)."_

We need to change the ”Mozilla Project" part to "Librefox Project" or similar, whatever intika has in mind here should be applied. Furthermore, as long as there is no Librefox website, I think the link leading to the Mozilla homepage should be replaced with this GitHub page.

Furthermore, I noticed that the Waterfox project has a sentence in the "About Waterfox" version info / update checking window which states the following:

_"Waterfox is not associated with Mozilla."_

It is at the bottom of the window, see here: https://www.ghacks.net/wp-content/uploads/2018/05/waterfox-56.2.0.png

I think we should include this sentence as well, just replacing "Waterfox" with "Librefox" here.

The "Know your rights" part leads to the **about:rights** page. There it states:

> Mozilla Firefox is free and open source software, built by a community of thousands from all over the world. There are a few things you should know:

We need to replace "Firefox" with "Librefox" here. Not sure what to do with the "community of thousands all over the world". Technically this is true, as thousands of people have contributed to the Firefox code upon which Librefox is built, but then, this statement might be a bit gross in relation to the Librefox project if we let it stand as is.

> Firefox is made available to you under the terms of the Mozilla Public License. This means you may use, copy and distribute Firefox to others. You are also welcome to modify the source code of Firefox as you want to meet your needs. The Mozilla Public License also gives you the right to distribute your modified versions.

We need to replace "Firefox" with "Librefox" throughout this paragraph, I think the rest is true still.

> You are not granted any trademark rights or licenses to the trademarks of the Mozilla Foundation or any party, including without limitation the Firefox name or logo. Additional information on trademarks may be found [here](https://www.mozilla.org/en-US/foundation/trademarks/policy/).

Again, we need to replace "Firefox" with "Librefox" here. Additionally, we need to replace "Mozilla Foundation" with "Librefox Project" or similar here. The "here" word has a link attached to it leading to a Mozilla page. As that info is applicable to Firefox and was not released by us, I think we shouldn't keep the last sentence at all.

> Some features in Firefox, such as the Crash Reporter, give you the option to provide feedback to Mozilla. By choosing to submit feedback, you give Mozilla permission to use the feedback to improve its products, to publish the feedback on its websites, and to distribute the feedback.

This can be deleted completely.

> How we use your personal information and feedback submitted to Mozilla through Firefox is described in the [Firefox Privacy Policy](https://www.mozilla.org/en-US/privacy/firefox/).

This does not seem to be applicable to the Librefox project at all, as almost all telemetry is gutted. However, once (if ever) Librefox introduces a working updater, the operating system and version of the browser must be submitted to the Librefox Project at least, as there is no other way to deliver the correct data. That being said, the Waterfox project has set up a privay notice that could inspire such a page for the Librefox project. See here: https://www.waterfoxproject.org/en-US/privacy/waterfox/ Some snippets of this are applicable to use, some are not (due to the gHacks-user.js being very strict in terms of the connections it allows).

> Some Firefox features make use of web-based information services, however, we cannot guarantee they are 100% accurate or error-free. More details, including information on how to disable the features that use these services, can be found in the [service terms](about:rights#webservices).

I leave it to developer to decide what to make of this. I have no idea, really. Especially the about:rights#webservices page should be reviewed and modified for ourpurposes.

> In order to play back certain types of video content, Firefox downloads certain content decryption modules from third parties.

This can be deleted completely.

**Comment by intika** [comment]
Thanks you a lot for your contribution and for taking time to locate all the places that need to be updated/changed/patched 

i am aware of the problem and this is scheduled for the next release  

here https://github.com/intika/Librefox/issues/26 and here https://github.com/intika/Librefox/issues/20

Those are urgent issue and they are the next step in this project :) 

Your post will be helpful ;)

I am closing this continue discussion here https://github.com/intika/Librefox/issues/26 ;)
