### ISSUE TITLE
I cant open Jellyfin pages:(

### ISSUE THREAD

**Issue by gerroon** [intika/Librefox#41]
Hi

Every browser except Librefox can access my Jellyfin (fork of Emby) no problem, but librefox shows me a constant loading circle when I try to open the Jellyfin web page :( The page load seems to take forever and never reaches to the landing page of Jellyfin

I am using LF on Win 10 x64 

thanks

**Comment by intika** [comment]
Thank you for your feedback :) 
i added this to the to-do list, it should be fixed in the next ;) it will be followed here https://github.com/intika/Librefox/issues/50
