### ISSUE TITLE
SSL_ERROR_UNSAFE_NEGOTIATION 

### ISSUE THREAD

**Issue by hubba900** [intika/Librefox#43]
Hello,

I can't open legal site like https://flow.polar.com/ and can't change options security.ssl.require_safe_negotiation to false. How I can use my favorite site?

**Comment by intika** [comment]
Hi, thank you for your feedback 

Delete those 2 lines from `mozilla.cfg` file then save and restart Librefox-Firefox
```

lockPref("security.ssl.require_safe_negotiation", true);
lockPref("security.ssl.treat_unsafe_negotiation_as_broken",	true);
```

The file is located in the Firefox install directory 

Let me know if you need further help
