### ISSUE TITLE
Edit contributors list

### ISSUE THREAD

**Issue by claustromaniac** [intika/Librefox#45]
https://github.com/intika/Librefox#about

Yesterday [I said I don't mind being listed in there](https://github.com/ghacksuserjs/ghacks-user.js/issues/542#issuecomment-449774318), but today I noticed that you accept donations, so I take that back. I'm glad that my work helps you and your project, and I'm grateful for your support :heart:, but so far [I've never made a contribution to this project specifically](https://github.com/intika/Librefox/graphs/contributors), and I don't accept donations for my work.

If I ever *do* contribute (I'm not discarding that possibility!), *then* I won't mind being in that list.

Thanks in advance.

**Comment by intika** [comment]
i removed the donation link and updated the about section https://github.com/intika/Librefox#about let me know if i can keep https://github.com/intika/Librefox#comparing-changes-and-updates or if you want any modification to what is written there

**Comment by claustromaniac** [comment]
Thank you. 

Just to be clear, I don't have anything against accepting donations for one's work, and even if I wanted to criticize you for that (which I don't), I'm in no position to do that! Like Pants, I just didn't want anyone to think that I take part in the project when I actually don't, that's all. If you want to accept donations, I'm good with that.
