### ISSUE TITLE
General direction of the project

### ISSUE THREAD

**Issue by samuel8941** [intika/Librefox#48]
https://forum.palemoon.org/viewtopic.php?f=4&t=21123&sid=75f9612f87b1ee17fa26e4a237c8c696#p158485

The palemoon creator took his time to list a couple of problematic things about this project.

> IMHO it's just another example of copy-pasta of insane configurations, and it's not something new or better or different than any of the other similar things I've seen out there. It's not even a rebuild, it's just reconfigured, and questionably so.

I agree with this criticism 100% and I suggest a general discussion about of where the project should be going.

There's only one niche where Librefox can be successful: Create an up-to-date Firefox-copy that does essentially the same; simply with less Mozilla, less Google and more customization, flexibility and control.

There isn't a demand for a locked-up hardcore user.js that makes browsing a pain.

**Comment by dimqua** [comment]
I can't agree completely, but he made a couple of a good points. I can elaborate if needed.

**Comment by elypter** [comment]
i would personally avoid any debatable privacy feature as default but add an easy way to switch it on or off. i agree with @samuel8941's niche. a daily use browser in its default settings should be primarily about usability. there are many settings that improve privacy and many features to re-enable that do not or only very rarely affect compatibility or usability. for the other settings a white or blacklist approach could be used but the browser should be about choice. it's mainly the people who want choice who install it in the first place.

**Comment by elypter** [comment]
>It's not even a rebuild, it's just reconfigured

thats not necessarily a disadvantage if this streamlines the process significantly. if this allows to have a relyably up to date version of firefox then this is a good way to go. it could also be a stepping stone for further independend modifications.

**Comment by John3** [comment]
oh come on librefox is totally ok i don't get it the complaint, is focused in privacy, security and is a **young project**... clearly is not for everybody. 

the palemoon creator complaint few thing for the average user and easy to use.

`I agree with this criticism 100% and I suggest a general discussion about of where the project should be going.`
I agree more with this project that other web browser. Keep the good work and don't sacrifice privacy or security for a few weeping users that want easy of use. The more the project grows, this gap it will be closer.

`General direction of the project`
privacy and security.

`Block third-party cookies. Nope, this will break login for some sites, break some payment gateways (forget about online shopping) etc.`
I do it all the time, you don't always need it.

`Completely disable the password manager (how does this improve privacy, exactly, by forcing users to type their credentials every time?)`
I not use the password manager is less secure, you can replace it with something else like KeepassXC or other alternative. For unimportant site like forum or whatever I have another DB from keepassXC... or just save it in a notepad at the end is not important right? :joy:  

This should go to a FAQ on how to enable the password manager.

`by forcing users to type their credentials every time?`
You do not need to type the credentials all the time, for example keepassxc can wrote it for you and so the other alternatives

`Completely disables integration with the add-ons site. `
It's ok, either way you can install add-ons. Mostly of the time I use the web author or addons.mozilla.org
:neutral_face: 
`So.. what if you WANT add-ons to improve your privacy?`
Like what add-ons? With the already customization you can well... avoid install a few add-ons. And if people are thinking ad-blocker, you can replace it with a better solution without messing with the web browser performance (other topic) again you can install add-ons...

`Completely disables extension updates`
It's depend sometimes the add-ons can mess with your stuff and broke it. I disable it and do a manual update after backup. This should go to a FAQ.

`Disables clipboard events, breaking many sites that use JS to place data on the clipboard`
It's ok for some, for me I don't use it. I have it disabled.
 
and the other reason should be an issue with the why and then add it to the FAQ pointing to the closed issue.

**Comment by dimqua** [comment]
> And if people are thinking ad-blocker, you can replace it with a better solution

What you mean?

**Comment by elypter** [comment]
for things like third party scripts and clipboard you could use black and whitelists and ask the user if there is no data. this doesnt sacrifice security or usability aside from very rare cases. we should look for technical solutions instead of making painful compromises.

**Comment by intika** [comment]
Interesting topic... https://github.com/intika/Librefox/issues/53 and https://github.com/intika/Librefox/issues/34 should take care of this
