### ISSUE TITLE
Consider collaboration with privacytools.io

### ISSUE THREAD

**Issue by c0rdis** [intika/Librefox#56]
Hi there! I'm a member of privacytools.io, and today I've created a discussion on https://github.com/privacytoolsIO/privacytools.io/issues/698. I think it would be quite beneficial to join the forces, review and merge existing tweaks from both projects (our recommended settings are listed here: https://www.privacytools.io/#about_config, and add-ons are available here: https://www.privacytools.io/#addons), and eventually refer you guys there. Feel free to comment here and there in the project and let us know what you think! Cheers!

**Comment by intika** [comment]
@c0rdis thank you for your feedback and your post in privacytools.io it's appreciated :) 
For the moment Librefox is very young and is susceptible of radical changes soon, there is 3, or 4 very important to-do (on the issues page) this will takes time 1 or 2 moth to get those important changes done, then we could reconsider this, but not in the current state of the project as it own current state does not represent the project.

**Comment by intika** [comment]
I will close this to keep the focus clear and avoid overwhelming the to-do list... after that i will look into all closed issues with "way-too-soon-for-this" and reopen relevant one at the time being :) but don't hesitate to reply :)
