### ISSUE TITLE
How to reset / uninstall?

### ISSUE THREAD

**Issue by Chippel** [intika/Librefox#64]
I didn't find it. Is there a reset button or something similar in order to reset it to the defaults?

**Comment by intika** [comment]
Yes just remove the files you added to your install i will update the readme

**Comment by intika** [comment]
- To uninstall, just remove the files you added to your Firefox's install directory (to know what file to remove just check the downloaded Librefox zip file)

**Comment by intika** [comment]
let me know if you need further assistance ;)
