### ISSUE TITLE
Set DuckDuckGo as default search engine

### ISSUE THREAD

**Issue by theel0ja** [intika/Librefox#65]

**Comment by Atavic** [comment]
No, use searx.me instead. Or one of these [instances](https://github.com/asciimoo/searx/wiki/Searx-instances). DDG has been criticized, due to the business past of the owner(s).

**Comment by samuel8941** [comment]
I agree, DDG is the way to go. Only search engine that comes close to Google regarding search results.

Startpage, Qwant, searx and others could be included as well, but DDG should be default.

**Comment by intika** [comment]
Personally i am not a fan of ddg, i will may be explain why in details later (some technical privacy issues) but one thing for sure is the choice will be given as always (the main focus on the next release is "the choice" so don't worry).
Also all search engines are profiling their users at a level or an other it's a must for them, and the more they use users data the more they are effective... but this is an other topic. 
The near outcome here is to come with the new build (first true release) then make it better as quick as possible, there is a lot to do before having something truly good (may be 6 months or more) but the first release will come before for sure :) 
All of this just to say that we are not in a situation like Opera where search engines are locked, you just set your default search engine one time with very few clicks and you are good to go even after updates so this or that as default does not really matter it is just kind a wink to the default search engine company and ddg is not that transparent.

**Comment by intika** [comment]
I will close this topic to avoid overwhelming the to-do list but feel free to keep answering ;)
