### ISSUE TITLE
Browser window doesn't save it's size and position between restarts.

### ISSUE THREAD

**Issue by 747iajc1k** [intika/Librefox#69]
Browser window resets it's size and position every time after restart, even if it was opened on full screen previously.
win10

**Comment by Atavic** [comment]
It's a *privacy.resistFingerprinting* feature, see: https://github.com/ghacksuserjs/ghacks-user.js/issues/220

**Comment by 747iajc1k** [comment]
@Atavic thanks!

**Comment by intika** [comment]
privacy.resistFingerprinting will be more at choice on the next version, it will be disabled by default and thus solve such issue ;)
