### ISSUE TITLE
removal some feature from source code

### ISSUE THREAD

**Issue by hesss5** [intika/Librefox#76]
Hi
thanks for great job and Librefox
from some recent version of Firefox there is folder called "features" there are several addon there
and with each new version of Firefox the addon in that folder reduced
as i noted seems Firefox restoring them back to it source.like activity-stream and pocket.com addon(and maybe some other addon reverted back silently)
are in Firefox.
so i may ask you please make one version with complete removal from source code of such useless addon
plus some other source code removal appreciated
like Firefox home content
![home](https://user-images.githubusercontent.com/23487445/50561342-c1c62100-0cd7-11e9-8855-b13e10e9c634.png)

and happy new year

**Comment by intika** [comment]
Hi, 

Yes i know about the addons that are integrated in the core i am removing them don't worry i added an issue about it https://github.com/intika/Librefox/issues/77 

For the home content there is no privacy issue nor telemetry nor connection to Mozilla once it's configured correctly so i'll keep that one and patch it to make sure it's an offline feature. 

Happy new year :)

**Comment by intika** [comment]
Let me know if you have other request ;)

**Comment by hesss5** [comment]
thank you finally somebody take care of them :1st_place_medal: 
i know its offlined but hope get this rid of this part too very useless addons can do this staff hope you add it to do list
ok other request whould be developer tool.can you make it as a feature addon?
or remove this part too.its very rarly used by end user this can be as seperate version
this make it very light version of it
also a question if i delete mozilla.cfg it work as normal without restriction?

thanks best regards

**Comment by intika** [comment]
there is a lot of things to be done right now i will see what i can do ;)
yes if you delete the file `mozilla.cfg` you get back the normal firefox
