### ISSUE TITLE
Allow toggling (some) about:config values

### ISSUE THREAD

**Issue by whalehub** [intika/Librefox#79]
I want to start Librefox with a maximized window which is currently not possible because the **about:config** value **privacy.resistFingerprinting** cannot be toggled from **true** to **false**. This minor problem is unfortunately annoying enough keeping me from using Librefox at the moment.

**Comment by intika** [comment]
Hi the locked settings can be edited just by changing their value in the `mozilla.cfg` file (https://github.com/intika/Librefox#edit-locked-settings) 
This is for the current version, but this will change on the next release, there will be a menu to do so and about:config wont be locked by default

**Comment by intika** [comment]
this will be followed here https://github.com/intika/Librefox/issues/34... i will close this, let me know if you need further assistance ;)
