### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by colbycdev** [intika/Librefox#80]
I see you've developed a version for Linux, and already it's in JavaScript. Porting to Android shouldn't be too hard from there.
The reason I ask is that I'm only on Android, and I only use Firefox because it has extension support(I use uBlock).

**Comment by F3000** [comment]
Hi , 

is Librefox generally supported on Android Devices ?

**Comment by Atavic** [comment]
See: https://github.com/intika/Librefox/issues/46

**Comment by colbycdev** [comment]
Duplicate of #8
