### ISSUE TITLE
Staying logged in after restarts

### ISSUE THREAD

**Issue by LennyPenny** [intika/Librefox#81]
Is there a setting I can tweak so session cookies can stay for at least a week or something? 

It's very annoying to always have to log in to sites like github or youtube with 2FA.

**Comment by Atavic** [comment]
See: https://github.com/intika/Librefox/blob/f9d761dba604ba61f1ab2902352a33eaf034356d/librefox/mozilla.cfg#L105

**Comment by LennyPenny** [comment]
Oh awesome thanks! 
Will there be a way in the future to merge local changes with the librefox ones? My changes will probably be overwritten by the next librefox update

**Comment by Atavic** [comment]
Yep. Create your very own personal ```user-overrides.js```

**Comment by LennyPenny** [comment]
Does this mean I will have to install ghacks alongisde librefox?

**Comment by Atavic** [comment]
```overrides.js``` is the correct name and it works [the same way as a user.js](https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs#editing_the_user-overridesjs_file) but is appended to it.

**Comment by Atavic** [comment]
overrides.js works the same way as a user.js but is appended to it, see [here](https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs#editing_the_user-overridesjs_file).

**Comment by Atavic** [comment]
*user-overrides.js* works the same way as a *user.js* but is appended to it, see:
https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs#editing_the_user-overridesjs_file

**Comment by LennyPenny** [comment]
Ah okay, so I will to use the theghacks updater script, as that functionality isn't included in librefox

**Comment by colbycdev** [comment]
I'd advise less code editing. End users generally don't mess with codel. If there is no visual setting for a desired functionality, they won't use the program

**Comment by intika** [comment]
@LennyPenny also check the line `defaultPref("privacy.sanitize.timeSpan", 0);` this could be edited directly on Firefox's settings page without editing the `mozilla.cfg` it's under "Preferences/Privacy/History/Clear history when Firefox closes"

Future version will have most of the settings integrated and manageable over the preferences pages... so you would may be need to redo your config for the future version but it would be easy and it will be kept over updates starting from the next release

**Comment by intika** [comment]
Don't hesitate to reply if you need further assistance ;)

**Comment by LennyPenny** [comment]
@intika thanks for that tip! I changed it in the settings page, but my history is still getting cleared every time I close librefox.

Is there a way to keep the history?

**Comment by intika** [comment]
Can you try under Preferences/Privacy/History select "Remember history" on the drop drown list

**Comment by LennyPenny** [comment]
Oooh thanks, got it now :)
