### ISSUE TITLE
Zoom is not remembered

### ISSUE THREAD

**Issue by gerroon** [intika/Librefox#84]
Hi

Does anyone have an issue with LF constantly resets the zoom levels after closeing the tab with a page and reopening the page ? I was using Firefox 60 on LInux and this was not an issue at all.

I have site specific zoom set to true

Any recommendations?

**Comment by Atavic** [comment]
> Does anyone have an issue with...

Yes, see:

https://github.com/ghacksuserjs/ghacks-user.js/blob/4604cf0d4ebc0aef81a89bbb971461018ed68370/user.js#L1655

> Any recommendations?

For preventing browser's fingerprinting, it is disabled. Users can click on it to make it *true*
this is one of the values that passd from Tor Project to Firefox.

**Comment by Atavic** [comment]
> Does anyone have an issue with...

Yes, see:

https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1655

> Any recommendations?

For preventing browser's fingerprinting, it is disabled: users can click on it to make it *true*.

This is one of the values that passed from Tor Project to Firefox.

**Comment by gerroon** [comment]
Ok thanks, I appreciate your help

**Comment by intika** [comment]
@gerroon let us know if you need further assistance :)
