### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP 

### ISSUE THREAD

**Issue by donuts12** [intika/Librefox#85]
This message keeps popping up on some websites and can't install any addons (tried right clicking and updating and it won't work)

**Comment by intika** [comment]
Hi, thank you for your feedback, first this will be fixed on next version. 

- Updates for addon is disabled, to install an addon or update it you can do it as usual from https://addons.mozilla.org/en-US/firefox/ by clicking the green button "Add to Firefox" on the addon's page that you want to install, let me know if it does not work in detail when you click "Add to Firefox"

- for `SSL_ERROR_NO_CYPHER_OVERLAP` you can open the file `mozilla.cfg` and remove the section `// Section : Security 2/3 ` and `// Section : Security 3/3` save the file and restart Firefox.

Let me know if you need further assistance ;)
