### ISSUE TITLE
[Suggestion] Add a snap package

### ISSUE THREAD

**Issue by b16r05** [intika/Librefox#88]
Not referencing but...  portableapp, deb, rpm, and appimage packages have been already suggested. I don't know if I missed it, but, a snap package would great. If it gets reviewed on OMG Ubuntu, that gets publicity... especially since Ubuntu is a widely used distribution and their snap packages solution used by many other Linux distros.

**Comment by intika** [comment]
We will see if this is really needed later, but for the portability purpose AppImage is enough... and to be honest a more advanced portable solution would be Flatpak... From what i know, Snaps are not very aligned with the privacy thing etc.

But later on if any one is willing to add a snap support, why not.

**Comment by b16r05** [comment]
Just wanted to put this out there. Yes, I also meant flatpak... I was forgetful : ) You know more about snaps privacy issues... probably because of shared libraries. Anyway, sounds like: flatpak>snaps>appimage, if one can actually compare them : )

**Comment by intika** [comment]
Yes, wait and see for the moment it's a little too soon to expand the builds
