### ISSUE TITLE
SSL error with https://lists.gnu.org/

### ISSUE THREAD

**Issue by gerroon** [intika/Librefox#92]
Does this mean gnu list site is using a lesser or old ssl encryption? I cant tell why Librefox is refusing to show the page.

```Secure Connection Failed

An error occurred during a connection to lists.gnu.org. Peer using unsupported version of security protocol. Error code: SSL_ERROR_UNSUPPORTED_VERSION

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by intika** [comment]
> Does this mean gnu list site is using a lesser or old ssl encryption? I cant tell why Librefox is refusing to show the page.

Hi, thank you for your feedback, and yes you guessed right... it's using an insecure ssl certificate (PKCS # 1 SHA-256 With RSA Encryption) 

[Is using “SHA-256 with RSA-2048 Encryption” a secure certificate hashing algorithm?](https://security.stackexchange.com/questions/122156/is-using-sha-256-with-rsa-2048-encryption-a-secure-certificate-hashing-algorit)

I will see how to implement an easy solution for this on next release...  

- You can open the file `mozilla.cfg` and remove the section `// Section : Security 2/3 ` and `// Section : Security 3/3` save the file and restart Firefox.

Let me know if you need further assistance ;)

**Comment by gerroon** [comment]
Damn you Gnu!
