### ISSUE TITLE
Can't copy text from Nextclouds text editor anymore

### ISSUE THREAD

**Issue by thrdroom** [intika/Librefox#98]
After installing Librefox i can't copy text in Nextclouds text editor anymore.
Im using Firefox 64 on MacOS.

Below is the html sourcecode sample of the text editor.
Please let me know if you need any further information.

`<div id="editor" class=" ace_editor ace-clouds"><textarea class="ace_text-input" autocorrect="off" autocapitalize="off" spellcheck="false" style="opacity: 0; height: 15px; width: 7px; left: 401px; top: 0px;" wrap="off"></textarea><div class="ace_gutter"><div class="ace_layer ace_gutter-layer ace_folding-enabled" style="margin-top: 0px; height: 459px; width: 40px;"><div class="ace_gutter-cell " style="height: 15px;">1</div></div><div class="ace_gutter-active-line" style="top: 0px; height: 15px;"></div></div><div class="ace_scroller" style="left: 40px; right: 0px; bottom: 0px;"><div class="ace_content" style="margin-top: 0px; width: 1056px; height: 459px; margin-left: 0px;"><div class="ace_layer ace_print-margin-layer"><div class="ace_print-margin" style="left: 564px; visibility: hidden;"></div></div><div class="ace_layer ace_marker-layer"><div class="ace_active-line" style="height:15px;top:0px;left:0;right:0;"></div></div><div class="ace_layer ace_text-layer" style="padding: 0px 4px;"><div class="ace_line_group" style="height:15px"><div class="ace_line" style="height:15px">This Text is not copiable!</div></div></div><div class="ace_layer ace_marker-layer"></div><div class="ace_layer ace_cursor-layer ace_hidden-cursors"><div class="ace_cursor" style="left: 361px; top: 0px; width: 7px; height: 15px;"></div></div></div></div><div class="ace_scrollbar ace_scrollbar-v" style="display: none; width: 22px; bottom: 0px;"><div class="ace_scrollbar-inner" style="width: 22px; height: 15px;"></div></div><div class="ace_scrollbar ace_scrollbar-h" style="display: none; height: 22px; left: 40px; right: 0px;"><div class="ace_scrollbar-inner" style="height: 22px; width: 1056px;"></div></div><div style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; white-space: pre; font: inherit; overflow: hidden;"><div style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; white-space: pre; font: inherit; overflow: visible;"></div><div style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; white-space: pre; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; font-size-adjust: inherit; font-kerning: inherit; font-optical-sizing: inherit; font-language-override: inherit; font-feature-settings: inherit; font-variation-settings: inherit; overflow: visible;">XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</div></div></div>`

**Comment by intika** [comment]
Thank you for your feedback, Nextclouds is probably accessing clipboard in write mode as well as read through java-script   

Under the file `mozilla.cfg` remove the lines 

`lockPref("dom.event.clipboardevents.enabled", false);`
and
`defaultPref("clipboard.autocopy", false);`

Save and restart the browser... v3 will fix this issue ;)

**Comment by intika** [comment]
let me know if you need further help ;)

**Comment by thrdroom** [comment]
Awesome! Thank you ;)
