### ISSUE TITLE
No addon update?

### ISSUE THREAD

**Issue by gerroon** [intika/Librefox#99]
Hi

Is the update for addons disabled? I cant seem to be able to search or update addons, I d onot mean auto update, talking about manual update.

thanks

**Comment by intika** [comment]
Yes it is disabled it's part of the feature that disable all connection to mozilla and addons auto-updates... i am aware of that and it will be fixed in v3... 
i added this to https://github.com/intika/Librefox/issues/3 and it will be followed there

**Comment by gerroon** [comment]
If the whole auto updates/phoning can be fully disabled that would be great, however keeping track of addons manually is a bit of hassle for sure

**Comment by intika** [comment]
it's not a problem i will find a way ;) as updating addons is important :+1:
